openapi: 3.0.3
info:
  title: API de Geolocalização
  version: 1.0.0
  description: Sistema de Geolocalização.

servers:
  - url: http://localhost:8080

paths:
  /location:
    get:
      summary: Pesquisa de logradouros por CEP.
      operationId: searchPlace
      tags:
        - Search
      parameters:
        - in: query
          name: cep
          schema:
            type: string
            pattern: '^[0-9]{8}$'
          required: true
      responses:
        '200':
          description: Local encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeolocationResponse'

components:
  schemas:
    GeolocationResponse:
      type: object
      properties:
        cep:
          type: string
        estado:
          type: string
        cidade:
          type: string
        bairro:
          type: string
        logradouro:
          type: string
        geolocalizacao:
          type: object
          properties:
            latitude:
              type: string
            longitude:
              type: string

    BrasilApiResponse:
      type: object
      properties:
        cep:
          type: string
        state:
          type: string
        city:
          type: string
        neighborhood:
          type: string
        street:
          type: string
        location:
          type: object
          properties:
            type:
              type: string
            coordinates:
              type: object
              properties:
                latitude:
                  type: string
                longitude:
                  type: string